set DB_SERVER=.
set DB_SOURCE=Test
set DB_USER=
set DB_PASS=
set COMPILE_PLATFORM_TARGET=AnyCPU
set BUILD_CONFIG=Debug


set DB_CONNECTION_STRING=-D:DB_SERVER=%DB_SERVER% -D:DB_SOURCE=%DB_SOURCE% -D:DB_USER=%DB_USER% -D:DB_PASS=%DB_PASS%
set COMPILE_PLATFORM_TARGET=-D:COMPILE_PLATFORM_TARGET=%COMPILE_PLATFORM_TARGET%
set BUILD_CONFIG=-D:BUILD_CONFIG=%BUILD_CONFIG%

:build
nant /f:rebuild.build %DB_CONNECTION_STRING% %COMPILE_PLATFORM_TARGET% %BUILD_CONFIG% -l:rebuild.log all
if %errorlevel% NEQ 0 goto err

:err
PAUSE